git add ObjectModel\JUnitTest\ObjectTest\abstract_1.txt
git add ObjectModel\JUnitTest\ObjectTest\abstract_2.txt
git add ObjectModel\JUnitTest\ObjectTest\check_1.txt
git add ObjectModel\JUnitTest\ObjectTest\check_2.txt
git add ObjectModel\JUnitTest\ObjectTest\check_3.txt
git add ObjectModel\JUnitTest\ObjectTest\date_1.txt
git add ObjectModel\JUnitTest\ObjectTest\date_2.txt
git add ObjectModel\JUnitTest\ObjectTest\editText_1.txt
git add ObjectModel\JUnitTest\ObjectTest\editText_2.txt
git add ObjectModel\JUnitTest\ObjectTest\editText_3.txt
git add ObjectModel\JUnitTest\ObjectTest\head_1.txt
git add ObjectModel\JUnitTest\ObjectTest\head_2.txt
git add ObjectModel\JUnitTest\ObjectTest\log_1.txt
git add ObjectModel\JUnitTest\ObjectTest\log_2.txt
git add ObjectModel\JUnitTest\ObjectTest\log_3.txt
git add ObjectModel\JUnitTest\ObjectTest\spinner_1.txt
git add ObjectModel\JUnitTest\ObjectTest\spinner_2.txt
git add ObjectModel\JUnitTest\ObjectTest\spinner_3.txt
git add ObjectModel\JUnitTest\ObjectTest\text_1.txt
git add ObjectModel\JUnitTest\ObjectTest\text_2.txt